<a href="https://colab.research.google.com/github/zqiaohe/datascience/blob/master/NaiveBayes_KNeighborsClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_digits, load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

In [5]:
from sklearn.model_selection import train_test_split, cross_val_score

In [22]:
X_d, y_d = load_digits(return_X_y=True)
X_b, y_b = load_breast_cancer(return_X_y=True)
X_d_train, X_d_test, y_d_train,  y_d_test = train_test_split(X_d, y_d, test_size = 0.25,  shuffle = False)
X_b_train, X_b_test, y_b_train,  y_b_test = train_test_split(X_d, y_d, test_size = 0.25)

In [7]:
cross_val_score(BernoulliNB(), X_d, y_d, cv = 3, scoring='accuracy')

array([0.83305509, 0.79966611, 0.83806344])

In [14]:
np.mean(cross_val_score(MultinomialNB(), X_d, y_d, cv = 3, scoring='accuracy'))

0.870895937673901

In [9]:
cross_val_score(GaussianNB(), X_d, y_d, cv = 3, scoring='accuracy')

array([0.8263773 , 0.79799666, 0.8163606 ])

In [10]:
cross_val_score(BernoulliNB(), X_b, y_b, cv = 3, scoring='accuracy')

array([0.62631579, 0.62631579, 0.62962963])

In [11]:
cross_val_score(MultinomialNB(), X_b, y_b, cv = 3, scoring='accuracy')

array([0.87894737, 0.89473684, 0.91005291])

In [13]:
np.mean(cross_val_score(GaussianNB(), X_b, y_b, cv = 3, scoring='accuracy'))

0.9367492806089297

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [23]:
clf = RandomForestClassifier(n_estimators=1000) 
clf.fit(X_d_train, y_d_train)
1-accuracy_score(y_d_test, clf.predict(X_d_test))

0.05777777777777782

In [32]:
from sklearn.neighbors import KNeighborsClassifier
nbrs = KNeighborsClassifier()
nbrs.fit(X_d_train, y_d_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [33]:
1-accuracy_score(y_d_test, nbrs.predict(X_d_test))

0.03555555555555556